# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0.xci
# IP: The module: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0.xci
# IP: The module: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pabitra/workspace/zcu102-project/zcu102-master-project/zcu102-master-project.srcs/sources_1/bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Zynq_MPSoC_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
