# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Base_Zynq_MPSoC/Base_Zynq_MPSoC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC || ORIG_REF_NAME==Base_Zynq_MPSoC} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0/Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_gpio_0_0/Base_Zynq_MPSoC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_axi_gpio_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_xbar_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_xbar_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_0/Base_Zynq_MPSoC_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_pc_0/Base_Zynq_MPSoC_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_pc_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_pc_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_1/Base_Zynq_MPSoC_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_1 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_1} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_ps8_0_axi_periph_0/Base_Zynq_MPSoC_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_ps8_0_axi_periph_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_99M_0/Base_Zynq_MPSoC_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_blk_mem_gen_0_0/Base_Zynq_MPSoC_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_blk_mem_gen_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_bram_ctrl_0_0/Base_Zynq_MPSoC_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_axi_bram_ctrl_0_0} -quiet] -quiet

# XDC: bd/Base_Zynq_MPSoC/Base_Zynq_MPSoC_ooc.xdc
